export const URL_PAGE = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/signup",
  DASHBOARD: "/dashboard",
  FORGOT: "/forgot",
  PRICING: "/pricing",
  WEBSITE: "/website",
  PROFILE: "/profile",
  CHECK: "/check",
  SMOKE_TESTING: "/smoke-testing",
  FUNCTIONALITY_TESTING: "/functionality-testing",
  BOOK_A_TESTER: "/book-a-tester",
  TEST_EXECUTION_REPORTS: "/test-execution-reports",
  TEST_CASES: "/test-cases",
  BUGS: "/bugs",
  CAREER: "/career",
  SOFTWARE_QUALITY_ASSURANCE: "/software-quality-assurance",
  SOFTWARE_TESTING: "/software-testing",
  WEBSITE_TESTING: "/website-testing",
  ABOUT_US: "/about-us",
  TERMS_AND_CONDITIONS: "/terms-and-coditions",
  PRIVACY: "/privacy",
  MY_ACCOUNT: "/my-account",
};
